<a href="https://colab.research.google.com/github/ra-vb/python_code/blob/main/Virtualcompetetion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [303]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [304]:
train_data=pd.read_csv('/content/train_ctrUa4K.csv')
test_data=pd.read_csv('/content/test_lAUu6dG.csv')
tr_data=train_data.copy()
ts_data=test_data.copy()

In [305]:
tr_data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [306]:
tr_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [307]:
tr_data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [308]:
# Separate numerical and categorical columns
numerical_cols = tr_data.select_dtypes(include=['number']).columns
categorical_cols = tr_data.select_dtypes(include=['object']).columns
numerical_cols

Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History'],
      dtype='object')

In [309]:
categorical_cols

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [310]:
for col in numerical_cols:
    tr_data[col] = tr_data[col].fillna(tr_data[col].median())
tr_data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [311]:
# prompt: find outliers and fill with mean
#AGE  150, 160

import numpy as np
# Calculate IQR for numerical columns
Q1 = tr_data[numerical_cols].quantile(0.25)
Q3 = tr_data[numerical_cols].quantile(0.75)
IQR = Q3 - Q1

# Define outlier boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = ((tr_data[numerical_cols] < lower_bound) | (tr_data[numerical_cols] > upper_bound)).sum()
print(outliers)

# Replace outliers with mean
for col in numerical_cols:
    mean_val = tr_data[col].mean()
    tr_data[col] = np.where((tr_data[col] < lower_bound[col]) | (tr_data[col] > upper_bound[col]), mean_val, tr_data[col])

ApplicantIncome      50
CoapplicantIncome    18
LoanAmount           41
Loan_Amount_Term     88
Credit_History       89
dtype: int64

In [312]:
tr_data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849.0,0.0,128.0,360.000000,1.000000,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583.0,1508.0,128.0,360.000000,1.000000,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000.0,0.0,66.0,360.000000,1.000000,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120.0,360.000000,1.000000,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000.0,0.0,141.0,360.000000,1.000000,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900.0,0.0,71.0,360.000000,1.000000,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106.0,0.0,40.0,342.410423,1.000000,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072.0,240.0,253.0,360.000000,1.000000,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583.0,0.0,187.0,360.000000,1.000000,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583.0,0.0,133.0,360.000000,0.855049,Semiurban,N

In [313]:
# Normalize numerical features (using MinMaxScaler)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
tr_data[numerical_cols] = scaler.fit_transform(tr_data[numerical_cols])
tr_data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,0.570528,0.000000,0.474104,1.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,0.443788,0.264515,0.474104,1.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,0.285314,0.000000,0.227092,1.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,0.243568,0.413612,0.442231,1.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,0.585644,0.000000,0.525896,1.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,0.275303,0.000000,0.247012,1.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,0.396036,0.000000,0.123506,0.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,0.793072,0.042098,0.972112,1.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,0.744119,0.000000,0.709163,1.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,0.443788,0.000000,0.494024,1.0,0.0,Semiurban,N

In [314]:
# Label encode categorical features
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for col in categorical_cols:
    tr_data[col] = encoder.fit_transform(tr_data[col])
tr_data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,1,0,0,0,0,0.570528,0.000000,0.474104,1.0,1.0,2,1
1,1,1,1,1,0,0,0.443788,0.264515,0.474104,1.0,1.0,0,0
2,2,1,1,0,0,1,0.285314,0.000000,0.227092,1.0,1.0,2,1
3,3,1,1,0,1,0,0.243568,0.413612,0.442231,1.0,1.0,2,1
4,4,1,0,0,0,0,0.585644,0.000000,0.525896,1.0,1.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,609,0,0,0,0,0,0.275303,0.000000,0.247012,1.0,1.0,0,1
610,610,1,1,3,0,0,0.396036,0.000000,0.123506,0.0,1.0,0,1
611,611,1,1,1,0,0,0.793072,0.042098,0.972112,1.0,1.0,2,1
612,612,1,1,2,0,0,0.744119,0.000000,0.709163,1.0,1.0,2,1
613,613,0,0,0,0,1,0.443788,0.000000,0.494024,1.0,0.0,1,0

In [315]:
tr_data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [316]:
#preprocessing test set
ts_data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.0,Urban
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.0,Urban
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,NaN,Semiurban
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.0,Rural
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.0,Rural

In [317]:
ts_data.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [318]:
ts_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             356 non-null    object
 2   Married            367 non-null    object
 3   Dependents         357 non-null    object
 4   Education          367 non-null    object
 5   Self_Employed      344 non-null    object
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB

In [319]:
# Separate numerical and categorical columns
numerical_cols1 = ts_data.select_dtypes(include=['number']).columns
categorical_cols1 = ts_data.select_dtypes(include=['object']).columns
numerical_cols1

Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History'],
      dtype='object')

In [320]:
categorical_cols1

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'Property_Area'],
      dtype='object')

In [321]:
for col in numerical_cols1:
    ts_data[col] = ts_data[col].fillna(ts_data[col].median())
ts_data.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
dtype: int64

In [322]:
Q1 = ts_data[numerical_cols1].quantile(0.25)
Q3 = ts_data[numerical_cols1].quantile(0.75)
IQR = Q3 - Q1

# Define outlier boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = ((ts_data[numerical_cols1] < lower_bound) | (ts_data[numerical_cols1] > upper_bound)).sum()
print(outliers)

# Replace outliers with mean
for col in numerical_cols1:
    mean_val = ts_data[col].mean()
    ts_data[col] = np.where((ts_data[col] < lower_bound[col]) | (ts_data[col] > upper_bound[col]), mean_val, ts_data[col])

ApplicantIncome      32
CoapplicantIncome     8
LoanAmount           18
Loan_Amount_Term     50
Credit_History       59
dtype: int64

In [323]:
# Normalize numerical features (using MinMaxScaler)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
ts_data[numerical_cols1] = scaler.fit_transform(ts_data[numerical_cols1])
ts_data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,0.686345,0.000000,0.386792,1.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,0.369090,0.284522,0.462264,1.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,0.599952,0.341426,0.849057,1.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,0.280778,0.482929,0.339623,1.0,1.0,Urban
4,LP001051,Male,No,0,Not Graduate,No,0.393089,0.000000,0.235849,1.0,1.0,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,0.481042,0.337064,0.400943,1.0,1.0,Urban
363,LP002975,Male,Yes,0,Graduate,No,0.498920,0.134484,0.410377,1.0,1.0,Urban
364,LP002980,Male,No,0,Graduate,No,0.389969,0.378035,0.462264,1.0,1.0,Semiurban
365,LP002986,Male,Yes,0,Graduate,No,0.599952,0.453907,0.613208,1.0,1.0,Rural
366,LP002989,Male,No,0,Graduate,Yes,0.576626,0.000000,0.330189,0.0,1.0,Rural

In [324]:
# Label encode categorical features
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for col in categorical_cols1:
    ts_data[col] = encoder.fit_transform(ts_data[col])
ts_data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0,1,1,0,0,0,0.686345,0.000000,0.386792,1.0,1.0,2
1,1,1,1,1,0,0,0.369090,0.284522,0.462264,1.0,1.0,2
2,2,1,1,2,0,0,0.599952,0.341426,0.849057,1.0,1.0,2
3,3,1,1,2,0,0,0.280778,0.482929,0.339623,1.0,1.0,2
4,4,1,0,0,1,0,0.393089,0.000000,0.235849,1.0,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
362,362,1,1,3,1,1,0.481042,0.337064,0.400943,1.0,1.0,2
363,363,1,1,0,0,0,0.498920,0.134484,0.410377,1.0,1.0,2
364,364,1,0,0,0,0,0.389969,0.378035,0.462264,1.0,1.0,1
365,365,1,1,0,0,0,0.599952,0.453907,0.613208,1.0,1.0,0
366,366,1,0,0,0,1,0.576626,0.000000,0.330189,0.0,1.0,0

In [325]:
ts_data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [326]:
tr_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    int64
 1   Gender             614 non-null    int64
 2   Married            614 non-null    int64
 3   Dependents         614 non-null    int64
 4   Education          614 non-null    int64
 5   Self_Employed      614 non-null    int64
 6   ApplicantIncome    614 non-null    float64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    int64
 12  Loan_Status        614 non-null    int64
dtypes: float64(5), int64(8)
memory usage: 62.5 KB

In [327]:
tr_data['Loan_Status'].value_counts()

Loan_Status
1    422
0    192
Name: count, dtype: int64

In [328]:
tr_data['Loan_Status'].value_counts(normalize=True)

Loan_Status
1    0.687296
0    0.312704
Name: proportion, dtype: float64

In [329]:
y= tr_data['Loan_Status'] #Labels / Target variable
x= tr_data.drop(columns=['Loan_Status'])  #features

In [330]:
#train ad test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [331]:
x_train.shape

(491, 12)

In [332]:
x_test.shape

(123, 12)

In [333]:
#model creation
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [334]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
print('Accuracy is', accuracy_score(y_test, y_pred))
print('Precision is', precision_score(y_test, y_pred))
print('Recall is', recall_score(y_test, y_pred))
print('f1 score is', f1_score(y_test,y_pred))

Accuracy is 0.7886178861788617
Precision is 0.7596153846153846
Recall is 0.9875
f1 score is 0.8586956521739131

In [335]:
r2 = lr.score(x_test, y_test)
r2

0.7886178861788617

In [336]:
import joblib
joblib.dump(lr, 'loan_model.pkl')

['loan_model.pkl']

**K-NEAREST NEIGHBOUR**

In [337]:
from sklearn.neighbors import KNeighborsClassifier
metric_k=[]
neighbors=np.arange(3,15)
for k in neighbors:
  classifier=KNeighborsClassifier(n_neighbors=k,metric='minkowski',p=2)
  classifier.fit(x_train,y_train)
  y_pred=classifier.predict(x_test)
  acc=accuracy_score(y_test,y_pred)
  metric_k.append(acc)

In [338]:
for k in neighbors:
  classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
  classifier.fit(x_train,y_train)
  y_pred=classifier.predict(x_test)
  acc=accuracy_score(y_test,y_pred)

In [339]:
print('Accuracy is', accuracy_score(y_test, y_pred))
print('Precision is', precision_score(y_test, y_pred))
print('Recall is', recall_score(y_test, y_pred))
print('f1 score is', f1_score(y_test,y_pred))

Accuracy is 0.5772357723577236
Precision is 0.6428571428571429
Recall is 0.7875
f1 score is 0.7078651685393258

**SVM**

In [340]:
from sklearn.svm import SVC
sv_clf=SVC(kernel='linear')
sv_clf.fit(x_train,y_train)

SVC(kernel='linear')

In [341]:
y_pred=sv_clf.predict(x_test)
print('Accuracy is', accuracy_score(y_test, y_pred))
print('Precision is', precision_score(y_test, y_pred))
print('Recall is', recall_score(y_test, y_pred))
print('f1 score is', f1_score(y_test,y_pred))

Accuracy is 0.7886178861788617
Precision is 0.7596153846153846
Recall is 0.9875
f1 score is 0.8586956521739131

In [342]:
import joblib
joblib.dump(sv_clf, 'loan_model_svm.pkl')

['loan_model_svm.pkl']

**Decision tree**

In [343]:
from sklearn.tree import DecisionTreeClassifier
dt_clf=DecisionTreeClassifier(random_state=42)
dt_clf.fit(x_train,y_train)
y_pred=dt_clf.predict(x_test)

In [344]:
y_pred=dt_clf.predict(x_test)
print('Accuracy is', accuracy_score(y_test, y_pred))
print('Precision is', precision_score(y_test, y_pred))
print('Recall is', recall_score(y_test, y_pred))
print('f1 score is', f1_score(y_test,y_pred))

Accuracy is 0.7073170731707317
Precision is 0.7619047619047619
Recall is 0.8
f1 score is 0.7804878048780488

**Random Forest**

In [345]:
from sklearn.ensemble import RandomForestClassifier
rf_clf1 = RandomForestClassifier(criterion='Entropy',n_estimators=20)
rf_clf1 = RandomForestClassifier()
rf_clf1.fit(x_train,y_train)

RandomForestClassifier()

In [346]:
y_pred=rf_clf1.predict(x_test)
print('Accuracy is', accuracy_score(y_test, y_pred))
print('Precision is', precision_score(y_test, y_pred))
print('Recall is', recall_score(y_test, y_pred))
print('f1 score is', f1_score(y_test,y_pred))

Accuracy is 0.7723577235772358
Precision is 0.7549019607843137
Recall is 0.9625
f1 score is 0.8461538461538461

In [347]:
import joblib
joblib.dump(rf_clf1, 'loan_model_random_forest.pkl')

['loan_model_random_forest.pkl']

In [348]:
ts_data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0,1,1,0,0,0,0.686345,0.000000,0.386792,1.0,1.0,2
1,1,1,1,1,0,0,0.369090,0.284522,0.462264,1.0,1.0,2
2,2,1,1,2,0,0,0.599952,0.341426,0.849057,1.0,1.0,2
3,3,1,1,2,0,0,0.280778,0.482929,0.339623,1.0,1.0,2
4,4,1,0,0,1,0,0.393089,0.000000,0.235849,1.0,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
362,362,1,1,3,1,1,0.481042,0.337064,0.400943,1.0,1.0,2
363,363,1,1,0,0,0,0.498920,0.134484,0.410377,1.0,1.0,2
364,364,1,0,0,0,0,0.389969,0.378035,0.462264,1.0,1.0,1
365,365,1,1,0,0,0,0.599952,0.453907,0.613208,1.0,1.0,0
366,366,1,0,0,0,1,0.576626,0.000000,0.330189,0.0,1.0,0

In [349]:
sample_submission_df = pd.read_csv('/content/sample_submission_49d68Cx.csv')
sample_submission_df

      Loan_ID Loan_Status
0    LP001015           N
1    LP001022           N
2    LP001031           N
3    LP001035           N
4    LP001051           N
..        ...         ...
362  LP002971           N
363  LP002975           N
364  LP002980           N
365  LP002986           N
366  LP002989           N

[367 rows x 2 columns]

In [350]:
from joblib import load
model = load('/content/loan_model.pkl')
pred_test = ts_data.drop(columns=['Loan_Status'], errors='ignore')

# Make predictions
predictions = model.predict(pred_test)

label_mapping = {0: 'N', 1: 'Y'}

# Convert numerical predictions to categorical labels
predictions_categorical = [label_mapping[pred] for pred in predictions]

# Save the updated sample submission file to a new CSV file
sample_submission_df = pd.read_csv('/content/sample_submission_49d68Cx.csv')
#sample_submission_df.to_csv('best_prediction.csv', index=False)
sample_submission_df['Loan_Status'] = predictions_categorical
sample_submission_df.to_csv('/content/best_prediction_logistic.csv', index=False)

In [351]:
from joblib import load
model = load('loan_model_svm.pkl')
pred_test = ts_data.drop(columns=['Loan_Status'], errors='ignore')

# Make predictions
predictions = model.predict(pred_test)

label_mapping = {0: 'N', 1: 'Y'}

# Convert numerical predictions to categorical labels
predictions_categorical = [label_mapping[pred] for pred in predictions]

# Save the updated sample submission file to a new CSV file
sample_submission_df = pd.read_csv('/content/sample_submission_49d68Cx.csv')
#sample_submission_df.to_csv('best_prediction.csv', index=False)
sample_submission_df['Loan_Status'] = predictions_categorical
sample_submission_df.to_csv('/content/best_prediction_svm.csv', index=False)

In [352]:
from joblib import load
model = load('loan_model_random_forest.pkl')
pred_test = ts_data.drop(columns=['Loan_Status'], errors='ignore')

# Make predictions
predictions = model.predict(pred_test)

label_mapping = {0: 'N', 1: 'Y'}

# Convert numerical predictions to categorical labels
predictions_categorical = [label_mapping[pred] for pred in predictions]

# Save the updated sample submission file to a new CSV file
sample_submission_df = pd.read_csv('/content/sample_submission_49d68Cx.csv')
#sample_submission_df.to_csv('best_prediction.csv', index=False)
sample_submission_df['Loan_Status'] = predictions_categorical
sample_submission_df.to_csv('/content/random_forest.csv', index=False)